import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Profile",
  description: "Generated by Kief Consultancy and Technology",
  openGraph: {
    title: "Profile",
    description: "Generated by Kief Consultancy and Technology",
    images: [
      {
        url: "/copy/logo1.png", // relative to public/ folder
        width: 1868,
        height: 664,
        alt: "Kief Consultancy Logo",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
